workspace:
  base: /go
  # Preserve the upstream path for Go
  path: src/github.com/jtblin/kube2iam

pipeline:
  test:
    image: golang:1.8.3
    commands:
      - make setup
      - make test
      - make check

  release:
    image: golang:1.8.3
    commands:
      - make cross
    when:
      event: tag

ecr:
  image: plugins/ecr
  repo: 258875347723.dkr.ecr.us-east-1.amazonaws.com/kube2iam
  registry: 258875347723.dkr.ecr.us-east-1.amazonaws.com
  region: us-east-1
  tags: ${DRONE_TAG}

# TODO: Enable this
#  slack:
#    image: plugins/slack
#    webhook: https://hooks.slack.com/services/...
#    channel: ci-notifications
